### ISSUE TITLE
Is this project not working anymore?

### ISSUE THREAD

**Issue by melame1a** [Mila432/Love-Live-School-Idol-Festival-ALL-STARS-Python-Bot#2]
![1](https://user-images.githubusercontent.com/105432739/168072535-b48b1e06-fad9-42be-8849-5de7a6e494ab.png)

Error in `/bootstrap/fetchBootstrap`. Is there a solution?

**Comment by Mila432** [comment]
https://github.com/Mila432/Love-Live-School-Idol-Festival-ALL-STARS-Python-Bot/commit/cc31864b4f94bfd92c043b21f699d672e0edfcc8

I don't think so

**Comment by melame1a** [comment]
I changed the server address. To `https://jp-real-prod-v4tadlicuqeeumke.llas.bushimo.jp/ep3023`

However, the response after login is 403 error.

It is estimated that session_key or calc_digest has been changed.

I tried to confirm this with ida, but libil2cpp.so is protected.
